# Generated by Django 4.1.6 on 2023-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_account_number_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(blank=True, default=66364),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=56409),
        ),
    ]
