# Generated by Django 4.1.6 on 2023-04-28 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 28, 9, 37, 3, 856943, tzinfo=datetime.timezone.utc)),
        ),
    ]
