# Generated by Django 4.1.6 on 2023-04-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='account_number',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
